"""
=============================================================
MySQL Tool
=============================================================

Purpose
-------
Safely execute READ-ONLY SQL queries generated by the AI Agent.

Responsibilities
----------------
✔ Read-only MySQL connection
✔ SQL validation (statement type + forbidden keyword scan)
✔ Statement classification
✔ EXPLAIN support (cost analysis + execution plan)
✔ Query cost analysis (full-table-scan warnings)
✔ MAX_EXECUTION_TIME hint injection for SELECT / WITH
✔ Safe execution with structured output
✔ Connection health checks
✔ Pretty-printed human-readable output

This tool DOES NOT perform schema discovery.
Schema discovery belongs to local_schema_tool.py
"""

import os
import re
import time
from typing import Dict, Any, List, Tuple, Optional

import mysql.connector
from mysql.connector import Error
from dotenv import load_dotenv

load_dotenv()


class MySQLTool:
    """
    Read-only MySQL execution engine for LLM-generated SQL.

    Features:
      • Validates every query against an allow-list + deny-list
      • Runs EXPLAIN before SELECT/WITH to detect expensive scans
      • Injects MAX_EXECUTION_TIME(5000) on SELECT/WITH
      • Returns uniform structured JSON for every operation
      • Pretty-prints human-readable output
    """

    ALLOWED_STATEMENTS: set = {
        "SELECT", "SHOW", "DESCRIBE", "DESC", "EXPLAIN", "WITH"
    }

    FORBIDDEN_KEYWORDS: set = {
        "INSERT", "UPDATE", "DELETE", "DROP", "ALTER", "CREATE",
        "TRUNCATE", "REPLACE", "RENAME", "GRANT", "REVOKE",
        "LOCK", "UNLOCK", "CALL", "EXECUTE", "LOAD", "LOAD_FILE"
    }

    MAX_EXECUTION_TIME_MS: int = 5000
    FULL_SCAN_ROW_THRESHOLD: int = 100_000
    LARGE_ROW_THRESHOLD: int = 500_000
    DEFAULT_ROW_LIMIT: int = 10_000

    def __init__(self):
        self.host = os.getenv("MYSQL_HOST", "localhost")
        self.port = int(os.getenv("MYSQL_PORT", "3306"))
        self.user = os.getenv("MYSQL_USER")
        self.password = os.getenv("MYSQL_PASSWORD")
        self.database = os.getenv("MYSQL_DATABASE")

        self.connection: Optional[mysql.connector.MySQLConnection] = None
        self.cursor: Optional[mysql.connector.cursor.MySQLCursorDict] = None

        self.connect()

    def connect(self) -> None:
        try:
            self.connection = mysql.connector.connect(
                host=self.host,
                port=self.port,
                user=self.user,
                password=self.password,
                database=self.database,
                autocommit=True,
                connection_timeout=10,
                use_pure=True,
            )
            self.cursor = self.connection.cursor(dictionary=True)
            print("[MySQLTool] Connected to MySQL.")
        except Error as e:
            raise RuntimeError(f"MySQL Connection Error: {e}")

    def _ensure_alive(self) -> None:
        try:
            if self.connection is None or not self.connection.is_connected():
                self.connect()
            else:
                self.connection.ping(reconnect=True, attempts=2, delay=1)
        except Error:
            self.close()
            self.connect()

    def close(self) -> None:
        if self.cursor:
            try:
                self.cursor.close()
            except Error:
                pass
            self.cursor = None
        if self.connection:
            try:
                self.connection.close()
            except Error:
                pass
            self.connection = None
        print("[MySQLTool] Connection closed.")

    def health_check(self) -> Dict[str, Any]:
        try:
            self._ensure_alive()
            self.cursor.execute("SELECT DATABASE() AS db")
            db = self.cursor.fetchone()["db"]
            return {"status": "healthy", "database": db}
        except Error as e:
            return {"status": "unhealthy", "error": str(e)}

    @staticmethod
    def _strip_comments(sql: str) -> str:
        sql = re.sub(r"/\*.*?\*/", " ", sql, flags=re.DOTALL)
        sql = re.sub(r"--[^\n]*", " ", sql)
        sql = re.sub(r"#[^\n]*", " ", sql)
        return sql

    def get_statement_type(self, sql: str) -> str:
        clean = self._strip_comments(sql).strip()
        if not clean:
            return "UNKNOWN"
        first_word = clean.split()[0].upper()
        return first_word

    def validate_sql(self, sql: str) -> Dict[str, Any]:
        stripped = sql.strip()
        if not stripped:
            return {"success": False, "error": "Empty SQL query."}

        statement = self.get_statement_type(stripped)
        if statement not in self.ALLOWED_STATEMENTS:
            return {
                "success": False,
                "error": f"{statement} statements are not allowed."
            }

        upper_sql = self._strip_comments(stripped).upper()
        for keyword in self.FORBIDDEN_KEYWORDS:
            if re.search(rf"\b{keyword}\b", upper_sql):
                return {
                    "success": False,
                    "error": f"Forbidden keyword detected: {keyword}"
                }

        return {"success": True, "statement": statement}

    def _run(self, sql: str) -> Tuple[List[Dict], List[str]]:
        self._ensure_alive()
        self.cursor.execute(sql)
        rows = self.cursor.fetchall()
        columns = [col[0] for col in self.cursor.description] if self.cursor.description else []
        return rows, columns

    def format_result(
        self,
        statement: str,
        rows: List[Dict],
        columns: List[str],
        execution_time: float,
        warnings: Optional[List[str]] = None,
        execution_plan: Optional[List[Dict]] = None,
    ) -> Dict[str, Any]:
        return {
            "success": True,
            "statement": statement,
            "row_count": len(rows),
            "columns": columns,
            "rows": rows[: self.DEFAULT_ROW_LIMIT],
            "execution_time_ms": round(execution_time * 1000, 2),
            "warnings": warnings or [],
            "execution_plan": execution_plan or [],
        }

    # ---------------------------------------------------------
    # Pretty-print helpers
    # ---------------------------------------------------------

    @staticmethod
    def _pretty_print(result: Dict[str, Any], table_name: Optional[str] = None) -> None:
        """
        Print query results in a clean human-readable format.
        Shows only relevant columns based on the query type.
        """
        if not result.get("success"):
            print(f"[ERROR] {result.get('error', 'Unknown error')}")
            return

        statement = result.get("statement", "UNKNOWN")
        rows = result.get("rows", [])
        columns = result.get("columns", [])
        row_count = result.get("row_count", 0)
        exec_time = result.get("execution_time_ms", 0)
        warnings = result.get("warnings", [])
        plan = result.get("execution_plan", [])

        # SHOW TABLES — compact list
        if statement == "SHOW" and len(columns) == 1 and "Tables_in" in columns[0]:
            print(f"\nFound {row_count} tables:")
            for row in rows:
                val = list(row.values())[0]
                print(f"  • {val}")
            return

        # DESCRIBE — compact schema format
        if statement in ("DESCRIBE", "DESC"):
            display_name = table_name or "table"
            pk_cols = [r["Field"] for r in rows if r.get("Key") == "PRI"]
            pk = pk_cols[0] if pk_cols else "(none)"

            col_names = [r.get("Field", "") for r in rows]
            col_list = ", ".join(col_names[:8])
            if len(col_names) > 8:
                col_list += f", ... ({len(col_names) - 8} more)"

            print(f"\n{display_name}  (Score=0.000)")
            print(f"   PK     : {pk}")
            print(f"   Columns: {len(rows)}")
            print(f"   Desc   : Schema definition for {display_name}.")
            print(f"   Relevant Columns: {col_list}")
            return

        # EXPLAIN / Cost Analysis — plan display
        if statement == "EXPLAIN" or (plan and not rows):
            print(f"\nExecution Plan ({len(plan)} steps):")
            for step in plan:
                table = step.get("table", "—")
                access = step.get("type", "—")
                est_rows = step.get("rows", "—")
                print(f"   Table: {table:<20}  Access: {access:<10}  Rows: {est_rows}")
            if warnings:
                print("\nWarnings:")
                for w in warnings:
                    print(f"   ⚠ {w}")
            return

        # Standard SELECT / WITH — compact summary + sample rows
        print(f"\nResult: {statement} | {row_count} rows | {exec_time} ms")

        if warnings:
            print("Warnings:")
            for w in warnings:
                print(f"   ⚠ {w}")

        if plan:
            print("Plan:")
            for step in plan:
                table = step.get("table", "—")
                access = step.get("type", "—")
                est_rows = step.get("rows", "—")
                print(f"   {table}: {access} (~{est_rows} rows)")

        if not rows:
            print("(no rows)")
            return

        print(f"\nRelevant Columns: {', '.join(columns)}")

        print("\nSample rows:")
        for i, row in enumerate(rows[:5]):
            vals = [str(row.get(col, "NULL"))[:25] for col in columns]
            print(f"   Row {i+1}: {' | '.join(vals)}")

        if row_count > 5:
            print(f"   ... and {row_count - 5} more rows")

    # ---------------------------------------------------------
    # EXPLAIN / Cost analysis
    # ---------------------------------------------------------

    def explain_query(self, sql: str) -> Dict[str, Any]:
        validation = self.validate_sql(sql)
        if not validation["success"]:
            return validation

        statement = validation["statement"]
        if statement not in ("SELECT", "WITH"):
            return {
                "success": False,
                "error": "EXPLAIN is only supported for SELECT / WITH statements."
            }

        try:
            self._ensure_alive()
            self.cursor.execute(f"EXPLAIN {sql}")
            plan = self.cursor.fetchall()
            return {
                "success": True,
                "statement": "EXPLAIN",
                "row_count": len(plan),
                "columns": ["id", "select_type", "table", "type", "possible_keys", "key", "key_len", "ref", "rows", "Extra"],
                "rows": plan,
                "execution_time_ms": 0,
                "warnings": [],
                "execution_plan": plan,
            }
        except Error as e:
            return {"success": False, "error": str(e)}

    def analyze_query_cost(self, sql: str) -> Dict[str, Any]:
        explain = self.explain_query(sql)
        if not explain["success"]:
            return explain

        warnings: List[str] = []
        for row in explain["execution_plan"]:
            access_type = row.get("type", "")
            estimated_rows = row.get("rows", 0) or 0
            table = row.get("table", "Unknown")

            if access_type == "ALL" and estimated_rows > self.FULL_SCAN_ROW_THRESHOLD:
                warnings.append(
                    f"Large full table scan detected on '{table}' "
                    f"(estimated rows: {estimated_rows:,})."
                )
            elif estimated_rows > self.LARGE_ROW_THRESHOLD:
                warnings.append(
                    f"Query may process approximately {estimated_rows:,} rows."
                )

        return {
            "success": True,
            "statement": "EXPLAIN",
            "row_count": len(explain["execution_plan"]),
            "columns": ["table", "type", "rows"],
            "rows": explain["execution_plan"],
            "execution_time_ms": 0,
            "warnings": warnings,
            "execution_plan": explain["execution_plan"],
        }

    # ---------------------------------------------------------
    # Statement executors
    # ---------------------------------------------------------

    def _execute_select(self, sql: str) -> Dict[str, Any]:
        analysis = self.analyze_query_cost(sql)
        if not analysis["success"]:
            return analysis

        sql = self._inject_max_execution_time(sql)

        start = time.perf_counter()
        rows, columns = self._run(sql)
        end = time.perf_counter()

        return self.format_result(
            statement="SELECT",
            rows=rows,
            columns=columns,
            execution_time=end - start,
            warnings=analysis["warnings"],
            execution_plan=analysis["execution_plan"],
        )

    @staticmethod
    def _inject_max_execution_time(sql: str) -> str:
        match = re.search(
            r"^(\s*/\*.*?\*/\s*)?(\s*)(SELECT|WITH)\b",
            sql,
            re.IGNORECASE,
        )
        if not match:
            return sql
        keyword_end = match.end()
        hint = f" /*+ MAX_EXECUTION_TIME({MySQLTool.MAX_EXECUTION_TIME_MS}) */"
        return sql[:keyword_end] + hint + sql[keyword_end:]

    def _execute_show(self, sql: str) -> Dict[str, Any]:
        start = time.perf_counter()
        rows, columns = self._run(sql)
        end = time.perf_counter()
        return self.format_result(
            statement="SHOW", rows=rows, columns=columns, execution_time=end - start
        )

    def _execute_describe(self, sql: str) -> Dict[str, Any]:
        start = time.perf_counter()
        rows, columns = self._run(sql)
        end = time.perf_counter()
        return self.format_result(
            statement="DESCRIBE", rows=rows, columns=columns, execution_time=end - start
        )

    def _execute_explain(self, sql: str) -> Dict[str, Any]:
        start = time.perf_counter()
        rows, columns = self._run(sql)
        end = time.perf_counter()
        return self.format_result(
            statement="EXPLAIN", rows=rows, columns=columns, execution_time=end - start
        )

    def execute_query(self, sql: str) -> Dict[str, Any]:
        validation = self.validate_sql(sql)
        if not validation["success"]:
            return validation

        statement = validation["statement"]

        try:
            if statement in ("SELECT", "WITH"):
                return self._execute_select(sql)
            elif statement == "SHOW":
                return self._execute_show(sql)
            elif statement in ("DESCRIBE", "DESC"):
                return self._execute_describe(sql)
            elif statement == "EXPLAIN":
                return self._execute_explain(sql)
            else:
                return {
                    "success": False,
                    "error": f"Unsupported statement: {statement}"
                }
        except Error as e:
            return {"success": False, "error": str(e)}

    # ---------------------------------------------------------
    # Demo — minimal, focused samples only
    # ---------------------------------------------------------

    def demo(self) -> None:
        print("\n" + "=" * 60)
        print("MySQL Tool Demo")
        print("=" * 60)

        print("\n--- Health Check ---")
        result = self.health_check()
        print(f"  Status : {result.get('status')}")
        print(f"  DB     : {result.get('database')}")

        print("\n--- DESCRIBE tenants ---")
        result = self.execute_query("DESCRIBE tenants")
        self._pretty_print(result, table_name="tenants")

        print("\n--- SELECT * FROM tenants LIMIT 3 ---")
        result = self.execute_query("SELECT * FROM tenants LIMIT 3")
        self._pretty_print(result)

        print("\n--- EXPLAIN SELECT * FROM tenants LIMIT 5 ---")
        result = self.explain_query("SELECT * FROM tenants LIMIT 5")
        self._pretty_print(result)

        print("\n--- Cost Analysis ---")
        result = self.analyze_query_cost("SELECT * FROM tenants LIMIT 5")
        self._pretty_print(result)

        print("\n--- Security Test (DELETE) ---")
        result = self.execute_query("DELETE FROM tenants")
        self._pretty_print(result)

        print("\n--- Security Test (DROP) ---")
        result = self.execute_query("DROP TABLE tenants")
        self._pretty_print(result)


if __name__ == "__main__":
    tool = MySQLTool()
    try:
        tool.demo()
    finally:
        tool.close()
        